apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jhipster-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/wbenhamid77/jhipster-sample-application
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
